version: "3.9"

services:
  backend:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - quiznet

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "8082:80"
    networks:
      - quiznet

networks:
  quiznet:
    driver: bridge

